### ISSUE TITLE
Attribution possibly incorrect on a dataset

### ISSUE THREAD

**Issue by RainfallNZ** [tethys-ts/tethysts#11]
dataset_id = 9a870e62ed798bac5d7c8df1
attributed to Southland, but owned by Otago. Suspect one is in error.
Super useful package!
Cheers

Tim

**Comment by mullenkamp** [comment]
Thanks Tim. I thought I had corrected that a while ago...obviously I did not ;)

**Comment by mullenkamp** [comment]
The dataset metadata has been updated.
