### ISSUE TITLE
Site ref of ECan site Burkes Creek (Milford Clandeboye) Milford-Clandeboye Ro

### ISSUE THREAD

**Issue by RainfallNZ** [tethys-ts/tethysts#13]
Hi Mike,

Another trivial issue.
The site ref is '66' for the ECan site with name " Burkes Creek (Milford Clandeboye) Milford-Clandeboye Ro"
All other ECan site references are 5 or 7 digits.
I suspect an error but it may be with the ECan data source.

Cheers

Tim

**Comment by mullenkamp** [comment]
Thanks for paying so much attension to the data!
For better or worse, I'm pretty sure this is the correct ECan reference number for this station. I have seen other stations with numbering that doesn't seem to follow the normal ECan numbering. For example, you can also find a station with thr reference number 2316 in that same streamflow dataset. I know this is correct. From what I remember when I was at ECan, there are  stations that have some legacy reason for having these odd reference numbers.
But thanks again for letting me know if you've found odd or incorrect things!
