### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'wkb_hex'

### ISSUE THREAD

**Issue by guopeng-jiang** [tethys-ts/tethysts#83]
This is an example from the basic usage in the documentation but returns 'AttributeError: 'numpy.int64' object has no attribute 'wkb_hex'. Maybe related to `shapely` version?

```python
dataset_id = 'b5d84aa773de2a747079c127'

lon = 172.0

lat = -42.8

distance = 0.2

my_stations = ts.get_stations(dataset_id, lat=lat, lon=lon, distance=distance)
```

**Comment by mullenkamp** [comment]
Hi,

Could you provide more info about the error and your package versions?
I can run the code without problems.
But I do vaguely remember this issue in the past...and I think you're right...try to update to the newest shapely version.

**Comment by guopeng-jiang** [comment]
My shapely version is 2.0.1. More info about the error: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[19], line 9
      5 lat = -42.8
      7 distance = 0.2
----> 9 my_stations = ts.get_stations(dataset_id, lat=lat, lon=lon, distance=distance)

File C:\Program Files\Anaconda3\envs\GISC\lib\site-packages\tethysts\main.py:269, in Tethys.get_stations(self, dataset_id, geometry, lat, lon, distance, version_date, from_date, to_date)
    266     stn_dict = {s_id: s for s_id, s in stn_dict.items() if pd.Timestamp(s['time_range']['to_date']) <= to_date1}
    268 ## Spatial query
--> 269 stn_ids = spatial_query(stn_dict, geometry, lat, lon, distance)
    271 if isinstance(stn_ids, list):
    272     stn_list1 = [stn_dict[s] for s in stn_ids]

File C:\Program Files\Anaconda3\envs\GISC\lib\site-packages\tethysts\utils.py:192, in spatial_query(stns, query_geometry, lat, lon, distance)
    190 if isinstance(distance, (int, float)):
    191     geom_query = geom_query.buffer(distance)
--> 192     stn_ids = get_intersected_stations(stns, geom_query)
    193 else:
    194     stn_ids = [get_nearest_station(stns, geom_query)]

File C:\Program Files\Anaconda3\envs\GISC\lib\site-packages\tethysts\utils.py:171, in get_intersected_stations(stns, geom_query)
    169 strtree = STRtree(geom1)
    170 res = strtree.query(geom_query)
--> 171 res_ids = [r.wkb_hex for r in res]
    173 stn_id_dict = {shape(s['geometry']).wkb_hex: i for i, s in stns.items()}
    175 stn_ids = [stn_id_dict[r] for r in res_ids]

File C:\Program Files\Anaconda3\envs\GISC\lib\site-packages\tethysts\utils.py:171, in <listcomp>(.0)
    169 strtree = STRtree(geom1)
    170 res = strtree.query(geom_query)
--> 171 res_ids = [r.wkb_hex for r in res]
    173 stn_id_dict = {shape(s['geometry']).wkb_hex: i for i, s in stns.items()}
    175 stn_ids = [stn_id_dict[r] for r in res_ids]

AttributeError: 'numpy.int64' object has no attribute 'wkb_hex'

**Comment by mullenkamp** [comment]
What are your other related package versions? tethysts, pandas, hdf5tools?
If you're not already using tethysts version 4.5.11, please upgrade to that.

**Comment by guopeng-jiang** [comment]
Thanks, just upgraded tethysts to 4.5.11 and it works. I think might worth updating the installation page [](https://tethysts.readthedocs.io/en/latest/installation.html) to clarify this https://tethysts.readthedocs.io/en/latest/installation.html
