### ISSUE TITLE
TypeError conlist() got an unexpected keyword argument 'min_items'

### ISSUE THREAD

**Issue by JohnnyRocket66** [tethys-ts/tethysts#87]
Running in Jupyterlab Version 3.5.3, after executing the following command

from tethysts import Tethys

tethysts installed version is 4.5.11
I get the same error with 4.5.12

Error details:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[16], line 1
----> 1 from tethysts import Tethys

File ~\anaconda3\lib\site-packages\tethysts\__init__.py:1
----> 1 from tethysts.main import Tethys
      2 from tethysts import utils

File ~\anaconda3\lib\site-packages\tethysts\main.py:21
     19 from s3tethys import get_object_s3, s3_client, decompress_stream_to_object
     20 from typing import List, Union
---> 21 import tethys_data_models as tdm
     22 import pathlib
     23 from time import time

File ~\anaconda3\lib\site-packages\tethys_data_models\__init__.py:1
----> 1 from tethys_data_models import permit, dataset, base
      2 from tethys_data_models.utils import key_patterns

File ~\anaconda3\lib\site-packages\tethys_data_models\permit.py:14
     12 import orjson
     13 from .utils import orjson_dumps
---> 14 from .geometry import geometry
     15 from . import base
     17 #########################################
     18 ### Models

File ~\anaconda3\lib\site-packages\tethys_data_models\geometry.py:16
     10 from pydantic import BaseModel, Field, HttpUrl, conlist
     11 # from hashlib import blake2b
     12 
     13 ################################################3
     14 ### Classes
---> 16 lat_lon = Union[conlist(float, min_items=2, max_items=3), conlist(int, min_items=2, max_items=3)]
     19 class Point(BaseModel):
     20     """
     21     Geojson geometry model for points.
     22     """

TypeError: conlist() got an unexpected keyword argument 'min_items'

**Comment by mullenkamp** [comment]
Sorry for the very late reply. That error is related to the pydantic package.
Try updating to the latest v1 package:
`conda install pydantic=1.10`

**Comment by mullenkamp** [comment]
I just tested this more thoroughly, and pydantic v2 has broken a lot of backwards compatibility. You'll definitely need to revert to the last v1.
