### ISSUE TITLE
ValueError: unrecognized engine h5netcdf must be one of: ['netcdf4', 'scipy', 'gini', 'store']

### ISSUE THREAD

**Issue by guopeng-jiang** [tethys-ts/tethysts#93]
```
my_stations = ts.get_stations(dataset_id = 'c5f55d97e71e7cd73295ad7f')
results = ts.get_results('c5f55d97e71e7cd73295ad7f', my_stations[0]['station_id'])
results
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 results = ts.get_results('c5f55d97e71e7cd73295ad7f', my_stations[0]['station_id'])
      2 results

File ~\AppData\Local\anaconda3\Lib\site-packages\tethysts\main.py:553, in Tethys.get_results(self, dataset_id, station_ids, geometry, lat, lon, from_date, to_date, from_mod_date, to_mod_date, version_date, heights, bands, squeeze_dims, output_path, compression, threads)
    550 xr.backends.file_manager.FILE_CACHE.clear()
    552 ## combine results
--> 553 xr3 = utils.results_concat(results_list, output_path=output_path, from_date=from_date, to_date=to_date, from_mod_date=from_mod_date, to_mod_date=to_mod_date, compression=compression)
    555 ## Convert to new version
    556 attrs = xr3.attrs.copy()

File ~\AppData\Local\anaconda3\Lib\site-packages\tethysts\utils.py:901, in results_concat(results_list, output_path, from_date, to_date, from_mod_date, to_mod_date, compression)
    898 h1 = result_filters(h1, from_date, to_date)
    899 h1.to_hdf5(output_path, compression=compression)
--> 901 xr3 = xr.open_dataset(output_path, engine='h5netcdf', cache=False)
    903 ## Deal with mod dates filters
    904 if ((from_mod_date is not None) or (to_mod_date is not None)) and ('modified_date' in xr3):

File ~\AppData\Local\anaconda3\Lib\site-packages\xarray\backends\api.py:552, in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)
    549 if from_array_kwargs is None:
    550     from_array_kwargs = {}
--> 552 backend = plugins.get_backend(engine)
    554 decoders = _resolve_decoders_kwargs(
    555     decode_cf,
    556     open_backend_dataset_parameters=backend.open_dataset_parameters,
   (...)
    562     decode_coords=decode_coords,
    563 )
    565 overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)

File ~\AppData\Local\anaconda3\Lib\site-packages\xarray\backends\plugins.py:205, in get_backend(engine)
    203     engines = list_engines()
    204     if engine not in engines:
--> 205         raise ValueError(
    206             f"unrecognized engine {engine} must be one of: {list(engines)}"
    207         )
    208     backend = engines[engine]
    209 elif isinstance(engine, type) and issubclass(engine, BackendEntrypoint):

ValueError: unrecognized engine h5netcdf must be one of: ['netcdf4', 'scipy', 'gini', 'store']

**Comment by mullenkamp** [comment]
I have no idea how you managed to install tethysts and not install the required dependency h5netcdf...
If you read the final line, that should give you some idea of the problem in most cases.
