### ISSUE TITLE
Dependency on fcntl package not available in windows

### ISSUE THREAD

**Issue by RainfallNZ** [tethys-ts/tethysts#96]
When importing tethysts on a windows 10 machine a ModuleNotFoundError was returned with "No Module named 'fcntl'.
It is imported as part of hdf5tools\core.py line 17.
Googling fcntl shows that it is not available for Windows.
The work around is to use linux.
I've added this same issue to the hdf5tools repository.

**Comment by mullenkamp** [comment]
Thanks Tim. I've fixed it (https://github.com/mullenkamp/hdf5-tools/pull/27). Use the new hdf5-tools version 0.4.4.
